### ISSUE TITLE
Can't import numpy error

### ISSUE THREAD

**Issue by sean-engelstad** [smdogroup/funtofem#186]

**Comment by A-CGray** [comment]
I think @timryanb might be able to help out here since TACS has pretty much exactly the same build process and I don't have this issue there. I don't use conda so the proposed solution here wouldn't fix my issue, I think numpy probably just needs to be specified as a build dependency somewhere

**Comment by A-CGray** [comment]
Adding an the `pyproject.toml` file from the TACS repo to F2F fixes the issue:
```toml
#pyproject.toml
[build-system]
# Minimum requirements for the build system to execute.
requires = ['setuptools>=45.0', 'wheel', 'cython>=0.29', 'oldest-supported-numpy', 'mpi4py==3.1.1']
```
